// <auto-generated />
using System;
using ChronoLogical.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoLogical.Api.Migrations
{
    [DbContext(typeof(ChronoLogicalContext))]
    partial class ChronoLogicalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ChronoLogical.Api.Model.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCode")
                        .HasDatabaseName("IX_TimeEntries_ProjectCode");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_TimeEntries_StartTime");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_TimeEntries_TaskId");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("IX_TimeEntries_DateRange");

                    b.ToTable("TimeEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
